from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
import json
from io import BytesIO

from database.connection import get_db
from database.schema import Scenario, User
from api.auth import get_current_user

# ReportLab imports
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

router = APIRouter(prefix="/reports", tags=["reports"])

@router.get("/download/{scenario_id}")
def download_scenario_report(
    scenario_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    scen = db.query(Scenario).filter_by(id=scenario_id).first()
    if not scen:
        raise HTTPException(status_code=404, detail="Scenario not found")

    # Fetch baseline metrics for comparison table
    baseline = db.query(Scenario).filter_by(status="baseline").first()
    baseline_metrics = {}
    if baseline and baseline.results:
        baseline_metrics = json.loads(baseline.results[0].metrics_json)

    metrics = {}
    recommendations = {"summary": "No recommendation found", "actions": []}
    if scen.results:
        metrics = json.loads(scen.results[0].metrics_json)
        recommendations = json.loads(scen.results[0].recommendations_json)

    # Initialize Buffer
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )

    # Setup styles
    styles = getSampleStyleSheet()
    
    # Custom Palette - Mirror City Premium Dark Blue
    primary_color = colors.HexColor("#0f172a")  # Slate 900
    accent_color = colors.HexColor("#2563eb")   # Blue 600
    text_color = colors.HexColor("#334155")     # Slate 700
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=26,
        leading=30,
        textColor=primary_color,
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSub',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=accent_color,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10.5,
        leading=15,
        textColor=text_color,
        spaceAfter=10
    )

    bold_body_style = ParagraphStyle(
        'BoldBodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10.5,
        leading=15,
        textColor=primary_color,
        spaceAfter=10
    )

    story = []

    # Title Page / Cover Section
    story.append(Paragraph("MIRROR CITY DIGITAL TWIN REPORT", title_style))
    story.append(Paragraph(f"<b>Scenario:</b> {scen.name}<br/><b>Generated by:</b> {current_user.email} (Role: {current_user.role})<br/><b>Status:</b> {scen.status.upper()}", subtitle_style))
    story.append(Spacer(1, 15))

    # Executive Summary Section
    story.append(Paragraph("1. Executive Summary", h1_style))
    exec_summary_text = (
        f"This report presents the simulated impacts of planning decisions defined in the scenario '{scen.name}'. "
        "The calculations are derived using a Graph Neural Network (GNN) model combined with a 10-Agent AI consensus engine. "
        "The objective is to foresee municipal service changes, traffic bottle-necks, and economic performance prior to physical infrastructure deployment."
    )
    story.append(Paragraph(exec_summary_text, body_style))
    story.append(Spacer(1, 10))

    # Proposed Elements Section
    story.append(Paragraph("2. Proposed Infrastructure Elements", h1_style))
    if scen.elements:
        elem_data = [["Asset Type", "Asset Name", "Est. Cost"]]
        for e in scen.elements:
            elem_data.append([
                e.type.replace("_", " ").title(),
                e.name,
                f"${e.cost:,.0f}" if e.cost > 0 else "$0 (Existing)"
            ])
            
        t_elem = Table(elem_data, colWidths=[120, 260, 120])
        t_elem.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#f8fafc")),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 9),
        ]))
        story.append(t_elem)
    else:
        story.append(Paragraph("No new planning elements proposed in this scenario.", body_style))
    story.append(Spacer(1, 15))

    # KPIs Comparison Table Section
    story.append(Paragraph("3. Scenario Performance Comparison", h1_style))
    
    # Prep comparison cells
    def get_val(metrics_dict, key, default="N/A"):
        val = metrics_dict.get(key)
        if val is None:
            return default
        if "cost" in key:
            return f"${val:,.0f}"
        if "growth" in key or "coverage" in key or "roi" in key:
            return f"{val}%"
        return str(val)

    comparison_data = [
        ["Key Performance Indicator (KPI)", "Baseline City State", f"Proposed: {scen.name}"],
        ["Traffic Congestion Score (0-100)", get_val(baseline_metrics, "traffic_score"), get_val(metrics, "traffic_score")],
        ["Average Commuter Time (mins)", get_val(baseline_metrics, "travel_time"), get_val(metrics, "travel_time")],
        ["Emergency Response Time (mins)", get_val(baseline_metrics, "emergency_response"), get_val(metrics, "emergency_response")],
        ["Healthcare Population Coverage", get_val(baseline_metrics, "population_coverage"), get_val(metrics, "population_coverage")],
        ["CO2 Daily Carbon Emissions (Tons)", get_val(baseline_metrics, "carbon_footprint"), get_val(metrics, "carbon_footprint")],
        ["Sustainability Score (0-100)", get_val(baseline_metrics, "sustainability_score"), get_val(metrics, "sustainability_score")],
        ["Disaster / Flood Risk Index", get_val(baseline_metrics, "risk_level"), get_val(metrics, "risk_level")],
        ["Economic Growth Forecast", "0.0%", get_val(metrics, "economic_growth")],
        ["Project Construction Cost", "$0", get_val(metrics, "cost")],
        ["Estimated ROI Rate", "0.0%", get_val(metrics, "roi")],
    ]

    t_comp = Table(comparison_data, colWidths=[240, 130, 130])
    t_comp.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#f8fafc")),
    ]))
    story.append(t_comp)
    story.append(Spacer(1, 15))

    story.append(PageBreak())

    # Multi-Agent Recommendations Section
    story.append(Paragraph("4. Explainable AI & Agent Recommendations", h1_style))
    story.append(Paragraph("<b>Consolidated AI Explanatory Narrative:</b>", bold_body_style))
    story.append(Paragraph(recommendations.get("summary", "No consolidated summary generated."), body_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("<b>Targeted Optimization Actions:</b>", bold_body_style))
    actions = recommendations.get("actions", [])
    if actions:
        for act in actions:
            title = act.get("title", "Action Item")
            desc = act.get("description", "")
            prio = act.get("priority", "Medium")
            story.append(Paragraph(f"• <b>[{prio} Priority] {title}</b>: {desc}", body_style))
    else:
        story.append(Paragraph("No targeted optimization suggestions generated.", body_style))

    # Build Document
    doc.build(story)
    buffer.seek(0)
    
    # Return File response
    filename = f"Mirror_City_Report_Scenario_{scenario_id}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
